### ISSUE TITLE
Please describe permission requirements

### ISSUE THREAD

**Issue by bhaelochon** [shikhir-arora/karma-simple#7]
What functionality does each of the permissions provide to the bot? Are all of them required?

**Comment by shikhir-arora** [comment]
Hi, the current permissions link includes the change nicknames permission for a feature that I was working on that hasn't come out yet. The only required permissions are:

- Read/Send Messages
- Embed Links (as the bot uses embeds)
- Add Reactions (for the NoKarma role option, otherwise this is not needed)

**Comment by bhaelochon** [comment]
Thank you!
